_wandb:
    value:
        cli_version: 0.23.1
        e:
            xukdvxw2n6d77q8ii72vxr0bnfdp5039:
                codePath: PRWMF.ipynb
                codePathLocal: PRWMF.ipynb
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "511050772480"
                        used: "360287813632"
                email: jummaahammed@gmail.com
                executable: C:\Users\user\anaconda3\python.exe
                git:
                    commit: 1650f9a7ed6a5c80917012f240f9c96ad808937a
                    remote: https://github.com/0-Lucifer/anamolies-detection-in-wafers-using-deep-learning-appraoch.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-f54cbecd-7e7c-d5b4-6109-775b33748f33
                host: DESKTOP-LM2G883
                memory:
                    total: "16886128640"
                os: Windows-11-10.0.26100-SP0
                program: PRWMF.ipynb
                python: CPython 3.13.5
                root: C:\Users\user\Desktop\project 465
                startedAt: "2025-12-07T22:14:05.527446Z"
                writerId: xukdvxw2n6d77q8ii72vxr0bnfdp5039
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
            "3":
                - 1
                - 2
                - 16
            "4": 3.13.5
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 1
lr:
    value: 0.0001
